# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -id {USF-XSim 62}  -string {{ERROR: [USF-XSim-62] 'compile' step failed with error(s) while executing 'C:/Users/Tyler/Desktop/Downloads/finalProject_ECEN_160L (1)/finalProject_ECEN_160L/finalProject_ECEN_160L.sim/sim_1/behav/compile.bat' script. Please check that the file has the correct 'read/write/execute' permissions and the Tcl console output for any other possible errors or warnings.}}  -suppress 
set_msg_config  -id {Vivado 12-1017}  -string {{WARNING: [Vivado 12-1017] Problems encountered:
1. PID not specified}}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Tyler/Desktop/Downloads/finalProject_ECEN_160L (1)/finalProject_ECEN_160L/finalProject_ECEN_160L.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Tyler/Desktop/Downloads/finalProject_ECEN_160L (1)/finalProject_ECEN_160L/finalProject_ECEN_160L.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/Tyler/Desktop/Downloads/finalProject_ECEN_160L (1)/finalProject_ECEN_160L/finalProject_ECEN_160L.srcs/sources_1/new/finalProject.v}}
synth_design -top alu -part xc7a35tcpg236-1
write_checkpoint -noxdef alu.dcp
catch { report_utilization -file alu_utilization_synth.rpt -pb alu_utilization_synth.pb }
