# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -id {USF-XSim 62}  -string {{ERROR: [USF-XSim-62] 'compile' step failed with error(s) while executing 'C:/Users/Tyler/Desktop/Downloads/finalProject_ECEN_160L (1)/finalProject_ECEN_160L/finalProject_ECEN_160L.sim/sim_1/behav/compile.bat' script. Please check that the file has the correct 'read/write/execute' permissions and the Tcl console output for any other possible errors or warnings.}}  -suppress 
set_msg_config  -id {Vivado 12-1017}  -string {{WARNING: [Vivado 12-1017] Problems encountered:
1. PID not specified}}  -suppress 
set_msg_config  -id {USF-XSim 62}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/tsmith4/Desktop/Final Final/finalProject_ECEN_160L/finalProject_ECEN_160L.cache/wt} [current_project]
set_property parent.project_path {C:/Users/tsmith4/Desktop/Final Final/finalProject_ECEN_160L/finalProject_ECEN_160L.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog {{C:/Users/tsmith4/Desktop/Final Final/finalProject_ECEN_160L/finalProject_ECEN_160L.srcs/sources_1/imports/Debouncer Files/clogb2.vh}}
set_property file_type "Verilog Header" [get_files {{C:/Users/tsmith4/Desktop/Final Final/finalProject_ECEN_160L/finalProject_ECEN_160L.srcs/sources_1/imports/Debouncer Files/clogb2.vh}}]
read_verilog -library xil_defaultlib {
  {C:/Users/tsmith4/Desktop/Final Final/finalProject_ECEN_160L/finalProject_ECEN_160L.srcs/sources_1/imports/Debouncer Files/meta_harden.v}
  {C:/Users/tsmith4/Desktop/Final Final/finalProject_ECEN_160L/finalProject_ECEN_160L.srcs/sources_1/imports/Hawker_files/Program_ROM.v}
  {C:/Users/tsmith4/Desktop/Final Final/finalProject_ECEN_160L/finalProject_ECEN_160L.srcs/sources_1/imports/Hawker_files/Instruction_Decoder.v}
  {C:/Users/tsmith4/Desktop/Final Final/finalProject_ECEN_160L/finalProject_ECEN_160L.srcs/sources_1/imports/Debouncer Files/debouncer.v}
  {C:/Users/tsmith4/Desktop/Final Final/finalProject_ECEN_160L/finalProject_ECEN_160L.srcs/sources_1/imports/finalProjectFiles/7segment.v}
  {C:/Users/tsmith4/Desktop/Final Final/finalProject_ECEN_160L/finalProject_ECEN_160L.srcs/sources_1/new/finalProject.v}
}
read_xdc {{C:/Users/tsmith4/Desktop/Final Final/finalProject_ECEN_160L/finalProject_ECEN_160L.srcs/constrs_1/imports/Labs/Basys3_XDC.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/tsmith4/Desktop/Final Final/finalProject_ECEN_160L/finalProject_ECEN_160L.srcs/constrs_1/imports/Labs/Basys3_XDC.xdc}}]

synth_design -top finalProject -part xc7a35tcpg236-1
write_checkpoint -noxdef finalProject.dcp
catch { report_utilization -file finalProject_utilization_synth.rpt -pb finalProject_utilization_synth.pb }
